<?php $this -> headTitle() -> append('Questions'); ?>
<?=$this -> render('header.phtml') ?>

<?php 
$id = isset($this->listOnce['id_questions']) ? $this->listOnce['id_questions'] : null;

?>
<div class="mainy">
<div class="row"> 
<div class="col-md-12">
    <a href="/admin/question" class="btn btn-primary">Back</a>
<div class="awidget">
    <h2><i class="icon-list color"></i> New Question </h2>
    <div class="awidget-body">
        
        <div class="awidget-body">
                              <form class="form-horizontal" role="form" action="/admin/question/new" method="post">
                              <input type="hidden" name="id_questions"  value="<?=$id?>"/>
                                <!-- <div class="form-group">
                                  <label class="col-lg-2 control-label">Description</label>
                                  <div class="col-lg-10">
                                    <input type="text" class="form-control" placeholder="Descriptions" name="description_question">
                                  </div>
                                </div> -->
                            <?php foreach($this->types as $value): ?>
                             <?php $opt_type[$value['id_type']] = $value['title_type']; ?>
                            <?php endforeach; ?>
                                
                                <div class="form-group">
                                  <label class="col-lg-2 control-label">Type</label>
                                  <div class="col-lg-10">
                                      <?=$this->select('id_type',$opt_type,isset($this->listOnce['id_type']) ? $this->listOnce['id_type'] : null,'form-control');?>
                                  </div>
                                </div>     
                                
                                <div class="form-group">
                                  <label class="col-lg-2 control-label">Answer</label>
                                  <div class="col-lg-10">
                                    <input type="text" class="form-control" placeholder="Answer question" name="answer_question" value="<?=isset($this->listOnce['answer_question']) ? $this->listOnce['answer_question'] : null ?>">
                                  </div>
                                </div>
                                

                                <div class="form-group">
                                  <label class="col-lg-2 control-label">Status</label>
                                  <div class="col-lg-10">
                                      <?=$this->select('status_question',array('1'=>'Enable','0'=>'Disable'),isset($this->listOnce['status_question']) ? $this->listOnce['status_question'] : 1,'form-control')?>
                                  </div>
                                </div>   

                                <div class="form-group">
                                  <label class="col-lg-2 control-label">Description</label>
                                  <div class="col-lg-10">
                                    <textarea class="form-control" name="description_question" rows="3" placeholder="Textarea"><?=isset($this->listOnce['description_question']) ? $this->listOnce['description_question'] : 1?></textarea>
                                  </div>
                                </div>    
                                
                                <div class="form-group">
                                  <div class="col-lg-offset-2 col-lg-10">
                                    <hr>
                                    <button type="submit" class="btn btn-success btn-lg">Save</button>
                                  </div>
                                </div>
                              </form>
                           </div>


    </div>
        </div>
    </div>
</div>
</div>
