<div class="header">
         <div class="container">
            <div class="row">
               <div class="col-md-3">
                  <!-- Logo -->
                  <div class="logo">
                     <h1><a href="index.html">Certifications</a></h1>
                  </div>
               </div>
               <div class="col-md-3">
                  <div class="row">
                    <div class="col-lg-10">
                      <div class="input-group form">
                           <!-- <input type="text" class="form-control" placeholder="Something..."> -->
                           <span class="input-group-btn">
                             <!-- <button class="btn btn-info" type="button">Search</button> -->
                           </span>
                      </div>
                    </div>
                  </div>
               </div>
               <div class="col-md-6">
                  <div class="navbar navbar-inverse" role="banner">
                      <div class="navbar-header">
                        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                          <span>Menu</span>
                        </button>
                      </div>
                      <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
                        <ul class="nav navbar-nav">
                          <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <b class="caret"></b></a>
                            <ul class="dropdown-menu animated fadeInUp">
                              <li><a href="#"><?=$this->session->name_user?></a></li>
                              <li><a href="/admin/index/logout">Logout</a></li>
                            </ul>
                          </li>
                        </ul>
                      </nav>
                  </div>
               </div>
            </div>
         </div>
      </div>
      
<div class="page-content blocky">
         <div class="container">

                  <div class="sidebar-dropdown"><a href="#">MENU</a></div>
                  <div class="sidey" style="">
                 
                 
                     <div class="side-cont">
                        <ul class="nav">
                            <!-- Main menu -->
                            <li class="current"><a href="/admin/home"><i class="icon-home"></i> Home</a></li>
                            <li><a href="/admin/question"><i class="icon-sitemap"></i> Questions</a></li>
                            <li><a href="/admin/alternative"><i class="icon-th"></i> Alternatives</a></li>
                            <li><a href="#"><i class="icon-file"></i> Language</a></li>
                            <li><a href="#"><i class="icon-bar-chart"></i> Type</a></li>
                            <li><a href="#"><i class="icon-th"></i> Role</a></li>
                            <li><a href="#"><i class="icon-sitemap"></i> User</a></li>
                        </ul>
                     </div>
                  </div>