<div class="header">
         <div class="container">
            <div class="row">
               <div class="col-md-3">
                  <!-- Logo -->
                  <div class="logo">
                     <h1><a href="index.html">Certifications</a></h1>
                  </div>
               </div>
               <div class="col-md-3">
                  <div class="row">
                    <div class="col-lg-10">
                      <div class="input-group form">
                           <input type="text" class="form-control" placeholder="Something...">
                           <span class="input-group-btn">
                             <button class="btn btn-info" type="button">Search</button>
                           </span>
                      </div>
                    </div>
                  </div>
               </div>
               <div class="col-md-6">
                  <div class="navbar navbar-inverse" role="banner">
                      <div class="navbar-header">
                        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                          <span>Menu</span>
                        </button>
                      </div>
                      <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
                        <ul class="nav navbar-nav">
                          <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-comments"></i> Chats <span class="label label-success">5</span> <b class="caret"></b></a>
                            <!-- Big dropdown menu -->
                            <ul class="dropdown-menu dropdown-big animated fadeInUp">
                              <!-- Dropdown menu header -->
                              <div class="dropdown-head">
                                 <span class="dropdown-title">Recent Chats</span>
                              </div>
                              <!-- Dropdown menu body -->
                              <div class="dropdown-body">
                                 <li><i class="icon-comments color"></i> <a href="#">Hi, How are you?</a><span class="label label-info pull-right">8.49</span></li>
                                 <li><i class="icon-comments color"></i> <a href="#">What are you doing?</a><span class="label label-info pull-right">6.49</span></li>
                                 <li><i class="icon-comments color"></i> <a href="#">Why are you doing this?</a><span class="label label-info pull-right">4.49</span></li>
                                 <li><i class="icon-comments color"></i> <a href="#">Mr.Baburae what is this?</a><span class="label label-info pull-right">1.49</span></li>
                              </div>
                              <!-- Dropdown menu footer -->
                              <div class="dropdown-foot text-center">
                                 <a href="#">View All Chats</a>
                              </div>
                            </ul>
                          </li>
                          <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i> Users <span class="label label-primary">5</span> <b class="caret"></b></a>
                            <!-- Big dropdown menu -->
                            <ul class="dropdown-menu dropdown-big animated fadeInUp">
                              <!-- Dropdown menu header -->
                              <div class="dropdown-head">
                                 <span class="dropdown-title">Members</span>
                              </div>
                              <!-- Dropdown menu body -->
                              <div class="dropdown-body">
                                 <li><i class="icon-user color"></i> <a href="#">Ashok</a><span class="label label-danger pull-right">Free</span></li>
                                 <li><i class="icon-user color"></i> <a href="#">Ravi Kumar</a><span class="label label-warning pull-right">Premium</span></li>
                                 <li><i class="icon-user color"></i> <a href="#">Baburae</a><span class="label label-primary pull-right">VIP</span></li>
                                 <li><i class="icon-user color"></i> <a href="#">Sunil Kumar</a><span class="label label-warning pull-right">Premium</span></li>
                              </div>
                              <!-- Dropdown menu footer -->
                              <div class="dropdown-foot text-center">
                                 <a href="#">All Members</a>
                              </div>
                            </ul>
                          </li>
                          <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <b class="caret"></b></a>
                            <ul class="dropdown-menu animated fadeInUp">
                              <li><a href="profile.html">Profile</a></li>
                              <li><a href="login.html">Logout</a></li>
                            </ul>
                          </li>
                        </ul>
                      </nav>
                  </div>
               </div>
            </div>
         </div>
      </div>
      
<div class="page-content blocky">
         <div class="container">

                  <div class="sidebar-dropdown"><a href="#">MENU</a></div>
                  <div class="sidey" style="">
                 
                 
                     <div class="side-cont">
                        <ul class="nav">
                            <!-- Main menu -->
                            <li class="current"><a href="/admin"><i class="icon-home"></i> Home</a></li>
                            <li><a href="#"><i class="icon-sitemap"></i> Questions</a></li>
                            <li><a href="#"><i class="icon-th"></i> Alternatives</a></li>
                            <li><a href="#"><i class="icon-file"></i> Language</a></li>
                            <li><a href="#"><i class="icon-bar-chart"></i> Type</a></li>
                            <li><a href="#"><i class="icon-th"></i> Role</a></li>
                            <li><a href="#"><i class="icon-sitemap"></i> User</a></li>
                            <!-- <li class="has_submenu">
                                 <a href="#">
                                    <i class="icon-sitemap"></i> Elements
                                    <span class="caret pull-right"></span>
                                 </a>
                                 <!-- Sub menu -->
                                 <!-- <ul>
                                    <li><a href="ui.html">User Interface</a></li>
                                    <li><a href="tables.html">Tables</a></li>
                                    <li><a href="form.html">Form</a></li>
                                </ul>
                            </li>  -->
                            <!-- <li><a href="#"><i class="icon-th"></i> Widgets</a></li>
                            <li class="has_submenu">
                                <a href="#">
                                    <i class="icon-file"></i> Pages
                                    <span class="caret pull-right"></span>
                                </a>
                                <ul>
                                    <li><a href="login.html">Login</a></li>
                                    <li><a href="register.html">Register</a></li>
                                    <li><a href="errorlog.html">Error Log</a></li>
                                    <li><a href="invoice.html">Invoice</a></li>
                                    <li><a href="404.html">404</a></li>
                                    <li><a href="makepost.html">Make Post</a></li>
                                    <li><a href="profile.html">Profile</a></li>
                                    <li><a href="media.html">Media</a></li>
                                </ul>
                            </li> 
                            <li><a href="calendar.html"><i class="icon-calendar"></i> Calendar</a></li>
                            <li><a href="gallery.html"><i class="icon-camera"></i> Gallery</a></li> -->
                        </ul>
                     </div>
                  </div>