<?php if ($this->pageCount): ?>
 <div class="pagination">
 <ul class="pagination pull-right">

<!-- First page link -->
<?php if (isset($this->first)): ?>
 <li><a href="<?php echo $this->url(array('page' => $this->first)); ?>">Primeiro</a></li>	
<?php else: ?>
 <li class="disabled"><a>Voltar</a></li>	
<?php endif; ?>
<!-- First page link -->

<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
 <li><a href="<?php echo $this->url(array('page' => $this->previous)); ?>">Voltar</a></li>	
<?php else: ?>
 <li class="disabled"><a>Voltar</a></li>	
<?php endif; ?>
<!-- Previous page link -->


<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
<?php if ($page != $this->current): ?>
<li><a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a></li>
<?php else: ?>
<li class="disabled"><a href="#"><?php echo $page; ?></a></li>
<?php endif; ?>
<?php endforeach; ?>
<!-- Numbered page links -->


<!-- Next page link -->
<?php if (isset($this->next)): ?>
<li><a href="<?php echo $this->url(array('page' => $this->next)); ?>">Proximo</a></li>
<?php else: ?>
<li class="disabled"><a href="#">Proximo</a></li>
<?php endif; ?>
<!-- Next page link -->

<!-- Next page link -->
<?php if (isset($this->last)): ?>
<li><a href="<?php echo $this->url(array('page' => $this->last)); ?>">Ultimo</a></li>
<?php else: ?>
<li class="disabled"><a href="#">Ultimo</a></li>
<?php endif; ?>
<!-- Next page link -->

</ul>
</div>
<?php endif; ?>