<?= $this->render('header.phtml')?>
<div class="mainy2">
<h2>Simulation from Magento Certification</h2>
	<div class="row"> 
		<div class="col-md-15">
			<div class="awidget">
<form action="/questions/validator" method="post">


<input type="hidden" name="qtd_question" value="<?=count($this->questions)?>" />
<?php foreach ($this->questions as $quest):?>
<p><h3><?=$quest['description_question']?></h3></p>
<?php $cont = 0;?>
<?php foreach ($this->alternatives as $alte){?>
	<?php if($alte['id_questions'] == $quest['id_questions']):?>
	<?php $arr =  $alte['form_alternative'] == 'radio' ? null : '[]'?>
	<p><strong><?=$alte['option_alternative']?></strong> - <input type="<?=$alte['form_alternative']?>" name="<?=$quest['id_questions'].$arr?>" value="<?=$alte['option_alternative']?>"> <?=htmlentities($alte['description_alternative'])?></p>
	<?php endif;?>
<?php }?>
<br>
<?php endforeach; ?>
<button type="submit" class="btn btn-primary btn-lg">Submit</button>
</form>
</div>
	</div>
		</div>
			</div>

<style>
.mainy2 {
	margin: 3% 8%;
}
</style>
