<?=$this->doctype('HTML5')?>
<html xmlns="http://www.w3.org/1999/xhtml">
   <meta charset="UTF-8" />
    <head>
        <?php echo $this->headTitle(' - Certifications'); ?>
        <?php $this->headMeta()
        ->appendName('charset','UTF-8') 
        ->appendName('viewport','width=device-width, initial-scale=1.0') ?>
        <!-- FIles css from skin -->
        <?php $this->headLink()->appendStylesheet('/skin/css/bootstrap.min.css')
                               ->appendStylesheet('/skin/css/animate.min.css')
                               ->appendStylesheet('/skin/css/bootstrap-datetimepicker.min.css')
                               ->appendStylesheet('/skin/css/bootstrap-switch.css')
                               ->appendStylesheet('/skin/css/font-awesome.min.css')
                               ->appendStylesheet('/skin/css/fullcalendar.css')
                               ->appendStylesheet('/skin/css/jquery.cleditor.css')
                               ->appendStylesheet('/skin/css/jquery.gritter.css')
                               ->appendStylesheet('/skin/css/jquery-ui.css')
                               ->appendStylesheet('/skin/css/prettyPhoto.css')
                               ->appendStylesheet('/skin/css/rateit.css')
                               ->appendStylesheet('/skin/css/style.css')
                               ->appendStylesheet('http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300')
                               ->appendStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,600italic,600')
         ?>
        <!-- FIles css from skin -->
        

        
        <?php echo $this->headMeta()?>
        <?php echo $this->headLink()?>
         <!--[if lte IE 8]>
             <script language="javascript" type="text/javascript" src="/skin/js/excanvas.min.js"></script>
         <![endif]-->
       
        
    </head>
    <body>
        
  