<?=$this->doctype('HTML5');?>
<html xmlns="http://www.w3.org/1999/xhtml">
        <meta charset="UTF-8" />
    <head>
        <?=$this->headTitle('ROBOZINHO  - DISCOVER'); ?>
        
        <?php $this->headLink()->appendStylesheet('http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css') 
                               ->appendStylesheet('http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css')
        
        ?>
        
        <?php $this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js')
                                 ->appendFile('http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js');
                                  ?>
        
    <?=$this->headLink();?>
    <?=$this->headScript();?>
    </head>
    <body>
        <div class="container">
            
        
        
    