<?php $this -> headTitle() -> append('Language'); ?>
<?=$this -> render('header.phtml') ?>

<div class="mainy">
<div class="row"> 
<div class="col-md-12">
    <a href="/admin/type" class="btn btn-primary">Back</a>
<div class="awidget">
    <h2><i class="icon-list color"></i> New Type </h2>
    <div class="awidget-body">
        
        <div class="awidget-body">
            

</div>
    </div>
        </div>
            </div>
                </div>
                    </div>